### PR TITLE
Add two methods to obtain pi using TaylorSeries and atan

### PR DESCRIPTION
**Pull request by lbenet**
I'm not sure how would you like the contributions, so I'm sending an ipynb notebook with the explanations. The whole idea is linked to the Taylor series of `atan`.

### CODE REVIEW

**Comment by simonbyrne** [comment]
Thanks, I worked this into the main notebook.

**Comment by lbenet** [comment]
Hi Simon,

Thanks for including it in the notebook. A tiny comment, which is important for my funding: Could you add my affiliation after the name? It should appear as: Instituto de Ciencias Físicas, Universidad Nacional Autónoma de México (UNAM). 

Aside from this, very nice notebook!

**Comment by simonbyrne** [comment]
Done!

**Comment by lbenet** [comment]
Thanks!

**Pull request closed without merging**
